from enum import Enum


class JobStatusEnum(str, Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    DONE = "DONE"
    FAILED = "FAILED"


class AgentNameEnum(str, Enum):
    VIDEO_PROCESSING = "VIDEO_PROCESSING"
    SPEECH_RECOGNITION = "SPEECH_RECOGNITION"
    TRANSCRIPT_CLEANER = "TRANSCRIPT_CLEANER"
    CONTENT_INTELLIGENCE = "CONTENT_INTELLIGENCE"
    TIMELINE_VALIDATOR = "TIMELINE_VALIDATOR"
    VIDEO_EDIT = "VIDEO_EDIT"
    SUBTITLE_STYLING = "SUBTITLE_STYLING"
    THUMBNAIL_FRAMES = "THUMBNAIL_FRAMES"
    SHORTS_EXTRACTION = "SHORTS_EXTRACTION"
    PACKAGING = "PACKAGING"
